;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		evil-append
		evil-backward-char
		evil-exit-visual-state
		evil-force-normal-state
		evil-forward-char
		evil-insert
		evil-mc-undo-all-cursors
		evil-next-line
		evil-normal-state
		evil-previous-line
		evil-visual-block
		evil-window-next
		general-simulate-C-w
		mc/mark-next-lines
		))

(setq mc/cmds-to-run-once
      '(
		general-simulate-M-x
		iedit-switch-to-mc-mode
		))
