#+title: My Emacs Journey
#+author: Hesham Can't Fly

* My vim experience
I was a vim user. I always have been a vim user. It started when I was doing programming on my android device, I was happy with Javascript and sometimes python, until i decided to learn React. at that time I was using Spck, it wasn't the best but it was the only best available option and you need to pay in order to use node. I found out later that i need to install Termux in order to use node so I did, but there's a problem.. the only way to do your react things are in Termux's home directory, so from that time been i decided to learn and use neovim. It was fascinating, the lsp itself was just enough for me to use neovim. after i bought my first laptop I learned vim motion and started hating on all non-keyboard based editor.
Now why i decided to switch to emacs? No reason lol, I just wanted to try something new :P

* My Emacs Journey
** Day 0: WTH
This is the beginning of my emacs journey, I opened Kitty and just typed ~sudo pacman -S emacs~, I wait for like 30 minutes cuz my internet connection is just like 100Kbps (If i were lucky) and I typed ~emacs testing.c~. i noticed that you can just type whatever you want directly, no normal mode, no visual mode, i thought it was just vim but with only insert mode, I opened youtube i watched a tutorial about emacs, just a couple minuts and i droped it. yes! there's no way that i will switch from using my beloved ~hjkl~ with ~C-f C-n C-p C-b~ or even arrow keys. I was a hasty judgment.

** Day 1: Evil
Couple days later and I after heard about some nice features about emacs like ~blimpy-mode~ I decided to retry emacs, went to my browser and i typed "How to start using Emacs as a vim user" and i ran into a redit post and one of the comments talked about a emacs package called Evil. Oh cool! Now how i can install a emacs package? What does "mode" mean in emacs? How I can config emacs?


