(deftheme my-theme
  "Created 2025-01-27.")

(custom-theme-set-faces
 'my-theme
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1c1e1f" :foreground "#d6d6d4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 128 :width normal :foundry "JB" :family "JetBrainsMono Nerd Font"))))
 '(cursor ((t (:background "#fb2874"))))
 '(fixed-pitch ((t (:family "JetBrainsMono Nerd Font" :foundry "JB" :width normal :height 130 :weight regular :slant normal))))
 '(variable-pitch ((t (:family "Noto Sans Mono" :foundry "GOOG" :width normal :height 130 :weight regular :slant normal))))
 '(escape-glyph ((t (:foreground "#66d9ef"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#fd971f"))))
 '(highlight ((t (:background "gold" :foreground "white"))))
 '(region ((t (:extend t :background "#4e4e4e"))))
 '(shadow ((t (:foreground "#555556"))))
 '(secondary-selection ((t (:extend t :background "#525254"))))
 '(trailing-whitespace ((t (:background "#e74c3c"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#fd971f"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#4A465D"))))
 '(font-lock-constant-face ((t (:foreground "#8AFF94"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#7f7f80" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:foreground "#FCD0A1"))))
 '(font-lock-keyword-face ((t (:foreground "#2D98CD")))) ; #2D98CD
 '(font-lock-negation-char-face ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#FCD0A1"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#2CA58D"))))
 '(font-lock-type-face ((t (:foreground "#8FFFE9"))))
 '(font-lock-variable-name-face ((t (:foreground "#fd971f"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "#fd971f"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#4e4e4e" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#d6d6d4" :background "#222323"))))
 '(mode-line ((t (:foreground "#d6d6d4" :background "#2d2e2e"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#fd971f"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#4e4e4e" :background "#171819"))))
 '(isearch ((t (:foreground "#1B2229" :background "#b6e63e"))))
 '(isearch-fail ((t (:weight bold :foreground "#1B2229" :background "#e74c3c"))))
 '(lazy-highlight ((t (:weight bold :foreground "#1B2229" :background "#9c91e4"))))
 '(match ((t (:weight bold :foreground "#b6e63e" :background "#1B2229"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'my-theme)
